default:
  python_linux: "/usr/bin/python3"
  python_windows: "C:/Python/Python39/python.exe"
  python_installation_stdout: "stdout_python_installation.txt"
  python_installation_stderr: "stderr_python_installation.txt"
